### ISSUE TITLE
Maps can be a source of infinite XP

### ISSUE THREAD

**Issue by saucylegs** [zDevelopers/ImageOnMap#116]
Maps that are larger than 1x1 are enchanted, which means you can put them through a grindstone for XP. If you keep doing /maptool, you can get an infinite number (or at least a large number) of maps and thus an infinite amount of XP.

Maybe an option for multiframe maps to not be enchanted?

**Comment by AmauryCarrade** [comment]
We can block grindstones for our maps, too.

**Comment by Vlammar** [comment]
> We can block grindstones for our maps,

That's what i have done. Will be fixed with cartographer table unzoom issues

**Comment by mailto-sage** [comment]
> > We can block grindstones for our maps,
> 
> That's what i have done. Will be fixed with cartographer table unzoom issues

How can i do it? 
>We can block grindstones for our maps

**Comment by Vlammar** [comment]
By adding a use case for grindstone, crafting and cartographer table. I've done a quick fix on the indev branch, but it's not perfect and need a bit of debugging .
