### ISSUE TITLE
Give map to player

### ISSUE THREAD

**Issue by quiquelhappy** [zDevelopers/ImageOnMap#117]
Hello! Could you **please** add a command for giving a map to a player? I want to implement this in my donation system so people can donate for getting a custom map. It would be cool if the map dropped or queued if the inventory is full, and if there is free space, it could be added directly into a player inv. For example /givemap <url> player_username

**Comment by Vlammar** [comment]
Yeah cool idea. We have a PR for getother that allow you to get a map from another player, it's pretty close to what you want to do here. https://github.com/zDevelopers/ImageOnMap/pull/48 The command as to be something like this. /maptool give <player where to find the map> <map name> <Player to give the map>

**Comment by Vlammar** [comment]
I'm waiting for final review #119 from @AmauryCarrade , the command will be /maptool give <Player> <MapName> and /maptool give <Player> <MapName> <PlayerMapPool> . The second can be used by command blocks and server console.

**Comment by quiquelhappy** [comment]
Good to know, will that allow to give maps to a player directly from an specific url? I can look into the code to make it happen if that's not the case with this new command :)

**Comment by Vlammar** [comment]
> 
> 
> Good to know, will that allow to give maps to a player directly from an specific url?
No it will allow to give a player"s map to another player. For instance /maptoolgive quiquelhappy Map-1 will give my mapitem to you named Map-1. You can add the player you want the map taken from at the end.

>
>
>I can look into the code to make it happen if that's not the case with this new command :)
Feel free .
