### ISSUE TITLE
.jar file won't open with java

### ISSUE THREAD

**Issue by elelang** [zDevelopers/ImageOnMap#118]
I've restarted my computer, redownloaded the file, tried jarfix, and still the file won't open with java :/ is there anyway to fix this?

**Comment by Vlammar** [comment]
A .jar file is basicaly an archive, you can open it with your favorite archive opener.

**Comment by AmauryCarrade** [comment]
Also, this executable JAR file is _not intended to be executed directly by Java_. This is a Bukkit plugin, to be loaded by a Bukkit-compatible Minecraft server (like Spigot). Executing the JAR with `java -jar ImageOnMap.jar` won't work, like any other Bukkit plugin.

**Comment by elelang** [comment]
so when i get it opened, what do i do next to get it in the game? im new to downloading stuff to my minecraft

**Comment by AmauryCarrade** [comment]
You don't need to unzip the ImageOnMap JAR file, ever.

First, get a working Bukki-compatible server (you can use Spigot: https://www.spigotmc.org/wiki/spigot-installation/ (https://www.spigotmc.org/wiki/spigot-installation/) , or Paper, simpler to get: https://papermc.io/downloads (https://papermc.io/downloads) ).
Then, run the server once. You'll get a lot of folders in the server's folder, including a “plugins” folder.
Pur the JAR file (as-is) in this folder, and voilà!

**Comment by elelang** [comment]
oh, so i can't use this plugin in a realm or singleplayer world?

**Comment by Vlammar** [comment]
No you need spigot/paper server to run a plugin.

**Comment by AmauryCarrade** [comment]
Realm/single does not support plugins, and we cannot do anything about this sadly.
