### ISSUE TITLE
Map Name Tags Show

### ISSUE THREAD

**Issue by KMacArthur** [zDevelopers/ImageOnMap#121]
MC v1.16.1
PaperMC v123
ImageOnMap v4.0

Creating a new map or using a preexisting one, when placing down the map the name tag shows. Maps that were in place prior to 1.16.1 upgrade are not affected. 

Additionally, Map appears to be incorrectly rotated on a freshly placed itemframe.
![IOM-moon](https://user-images.githubusercontent.com/4559489/88743985-192aae00-d114-11ea-9276-140500e5411f.PNG)

**Comment by Vlammar** [comment]
Fixed, will be added in the next update. Thanks for the report. It will only fix new map given with /maps (for the name issue)

**Comment by cyatarow** [comment]
When is the next update going to be released?
@Vlammar

**Comment by Vlammar** [comment]
Fixed in 4.1
