### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by GriffinCodes** [zDevelopers/ImageOnMap#127]
Cloning and building the current version produces a [compilation error](https://paste.bnn.gg/somac.yaml)

**Comment by Vlammar** [comment]
getOfflinePlayerParameter(int ) is a new method on zLib but I still have issues with it. I will try to update zLib tonight

**Comment by Vlammar** [comment]
Fixed with quartzlib 0.0.2 the method name change to fetchOfflinePlayer
