### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by ghost** [zDevelopers/ImageOnMap#134]
Hi,
I want to revoke everyone the permission to create/delete maps, for that I'm using LuckPerms with this command (for delete):

`lp group default permission set imagetomap.delete false`

but I'm still able to delete maps, and im not OP.

What's my Mistake?

**Comment by Vlammar** [comment]
You nammed imageonmap imageTOmap

**Comment by ghost** [comment]
Thanks, I'm an idiot.
