### ISSUE TITLE
1.16.5 Support

### ISSUE THREAD

**Issue by partydev** [zDevelopers/ImageOnMap#141]
Please update this plugin to work with 1.16.5. Current issue seems to be that it tries to merge old maps with new maps that are created.

**Comment by Vlammar** [comment]
Does by merging you are refering to this issue  #86 ? The plugin works in 1.16, the issue of 86# is mainly caused because bukkit is slow to update the idcount.dat file that is used by the game to keep track of the last map id generated

**Comment by partydev** [comment]
> 
> 
> Does by merging you are refering to this issue #86 ? The plugin works in 1.16, the issue of 86# is mainly caused because bukkit is slow to update the idcount.dat file that is used by the game to keep track of the last map id generated

The problem is that we cannot create any new maps larger than 1 map without this happening. This only started happening for us when we moved from 1.16.4 to 1.16.5.

**Comment by 0xicl33n** [comment]
![image](https://user-images.githubusercontent.com/2192160/108638051-302f4580-7442-11eb-816d-006ee05b72a0.png)

Can confirm that after updating to 1.16.5, the plugin no longer allows us to `/maptool list` to look  at previously created maps. sure we can make new ones but are unable to rename them. [Here](https://mclo.gs/7We3y9Q) is the error log

**Comment by Vlammar** [comment]
I was pretty sure that we stopped using REGISTRY with the 4.0-pre2, @AmauryCarrade
@0xicl33n Can you check if you are using the 4.0 and not the 4.0 pre1 or 4.0 pre2 ?

**Comment by Vlammar** [comment]
> 
> 
> > Does by merging you are refering to this issue #86 ? The plugin works in 1.16, the issue of 86# is mainly caused because bukkit is slow to update the idcount.dat file that is used by the game to keep track of the last map id generated
> 
> The problem is that we cannot create any new maps larger than 1 map without this happening. This only started happening for us when we moved from 1.16.4 to 1.16.5.
Can't reproduce this issue, I'm running on 1.16.5 and on the last spigot build. Does vanilla maps have broken ?

**Comment by 0xicl33n** [comment]
`/maptool list` does not work but `/maptool explore` does.  downloaded from the latest release on git just now. can close this since `explore` works in place of `list`

**Comment by partydev** [comment]
It was related to our database just being messed up. We wiped everything entirely and it began working fine.
