### ISSUE TITLE
Map Name Tags Show

### ISSUE THREAD

**Issue by Spinbab** [zDevelopers/ImageOnMap#142]
Hi, I saw someone had the same issue as me, and it was closed because it was fixed in 4.1, but I can't find Version 4.1 anywhere?
Anyway, since I updated my server to 1.16, all maps show the name tag "Map" above them. This doesn't apply to maps made prior to the update unless they are taken off the item frame and placed again. This doesn't apply to splatter maps either. How do I fix this?

**Comment by Vlammar** [comment]
We are a bit late with the 4.1. But this is fixed in the current indev branch. The issue was that I somehow deleted the line that prevent map from being renamed as "Map".

**Comment by Vlammar** [comment]
Fixed in 4.1
