### ISSUE TITLE
[Bug] Poster can't be placed on the floor

### ISSUE THREAD

**Issue by CKFA** [zDevelopers/ImageOnMap#143]
As title mentioned, poster map cannot be placed on the floor.

ImageOnMap Version 4.0 pre2
Minecraft 1.16.4

**Comment by AmauryCarrade** [comment]
[This is already implemented, but in 4.0](https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.0) (you're using 4.0-pre2, i.e. not the latest version).

Thanks anyway!
