### ISSUE TITLE
Inventory Problem

### ISSUE THREAD

**Issue by hideki2k02** [zDevelopers/ImageOnMap#148]
EDIT: Turns out the problem is with the whole inventory system and not GMusic itself
Server Version: Paper 1.16.5 472

I was using GMusic on my server with no problems, but after i ran the command below GMusic simply stopped working. 

/tomap insert_doge_image_link.png resize-stretched 3 3

None of the musics would play and the first 3x3 slots of the GUI would turn into the map that i just created.
Problem persisted until total server restart.

**Comment by Vlammar** [comment]
Hello, do you have an error in the console? Does the IoM command throw an error?

**Comment by hideki2k02** [comment]
No errors, GMusic just stops working

**Comment by hideki2k02** [comment]
Turns out the problem is with the whole inventory system and not GMusic itself, i'm updating the report

**Comment by Vlammar** [comment]
Maybe the last update of IoM has solved part of your issue. I fixed an inventory bug that may be related to this issue

Feel free to reopen if this is still a problem with ImageOnMap 4.1.1+.
