### ISSUE TITLE
[Feature Request] Permissions for number of maps 

### ISSUE THREAD

**Issue by DereC4** [zDevelopers/ImageOnMap#154]
I'm not sure if this is a thing yet but this way certain groups could be allowed to make more maps than others instead of everyone having a single limited number of maps they could make.

**Comment by Vlammar** [comment]
As far as I know you can't make permission like plugin.size=42 you are limited to this kind of permissions plugin.size.1, plugin.size.2 ... This is not a good solution for obvious reasons (need to check a lot of perms, slow, not user friendly).

**Comment by AmauryCarrade** [comment]
We could add something like Essentials: add a configuration option like this:

```yaml
map-limits:
    cats: 2000
    dogs: 1200
    ferrets: -1
```

and allow to give the `imageonmap.map-limits.cat` to limit to 2000 maps.

This being said, I want to remind you that starting with Minecraft 1.13, the maps limit is more than two _billions_. That's an enormous number, more than you could imagine (all ImageOnMap installations _combined_ use approx. 1% of this _per-server_-limit). So, is this really needed? Or are you asking for this feature to limit players without technical considerations?

**Comment by DereC4** [comment]
Limiting players so that they cant spam that many maps at once because it's happened before already unfortunately (and large maps)

**Comment by Vlammar** [comment]
It seems that it's possible to get a player list of perm . That make this feature trivial, a permission like ImageOnMap.mapSize.14 is now something doable

**Comment by Vlammar** [comment]
Done !
You can limit the number of map used and the number of image like this:
- imageonmap.maplimit.100 won't allow a player with more than 100 maps to make new maps
- imageonmap.imagelimit.10 same but with a limit on the number of image in the player map store
By default without permission node I set the limit to 2147483647. If there are more than one permission node set to true for a player I take the first one found.

**Comment by DereC4** [comment]
Nice
