### ISSUE TITLE
new version message at login not properly formatted

### ISSUE THREAD

**Issue by Azami7** [zDevelopers/ImageOnMap#160]
The login message for ops when there is a new version of ImageOnMap is not properly formatted. It shows up as json.

See screenshot:
<img width="1233" alt="Screen Shot 2021-04-10 at 5 49 23 PM" src="https://user-images.githubusercontent.com/26971562/114288576-182d7880-9a26-11eb-944f-390e33eda1f1.png">

**Comment by AmauryCarrade** [comment]
Hello, this is already being fixed on zDevelopers/QuartzLib#75. A fix should be published tomorrow.

Unfortunately we won't be able to back-port this to older versions.

Thanks!

**Comment by Azami7** [comment]
Great, thanks. I was just coming to add the stack trace I found related to this. :)

**Comment by AmauryCarrade** [comment]
We have everything we need now, but that's really nice of you!
