### ISSUE TITLE
ImageOnMap 4.1 reports as 4.0, leading to an update message on latest update

### ISSUE THREAD

**Issue by Nuyube** [zDevelopers/ImageOnMap#161]
I downloaded the release ImageOnMap-4.1.jar from the Releases tab from this repo, and I'm still getting messages that I'm running an out of date version. 
![image](https://user-images.githubusercontent.com/81436002/114293656-ffdd4e00-9a65-11eb-94e4-3e8408e4684b.png)
![image](https://user-images.githubusercontent.com/81436002/114293690-21d6d080-9a66-11eb-9c58-a7722117acab.png)

**Comment by AmauryCarrade** [comment]
Fixed in #158 and #159. Thanks! We'll publish a new release today, we have another detail to fix before.
The plugin will still work as expected and only server administrators see this message.
