### ISSUE TITLE
Update message error

### ISSUE THREAD

**Issue by EpicPlayerA10** [zDevelopers/ImageOnMap#162]
I downloaded the latest version ImageOnMap-4.1.jar and i have this error in console when admin joins to server.
![Zrzut ekranu 2021-04-11 151335](https://user-images.githubusercontent.com/62206933/114305437-82065a80-9ad8-11eb-9967-3284054d4cfe.png)

Plugin also sends me a broken message:

![Zrzut ekranu 2021-04-11 151731](https://user-images.githubusercontent.com/62206933/114305589-0f49af00-9ad9-11eb-9aba-b35573a7ed09.png)

My server is running on Paper 1.16.5

**Comment by AmauryCarrade** [comment]
Already fixed in zDevelopers/QuartzLib#74; we'll release a new 4.1.1 version today.
The plugin will still work as expected and only server administrators see this message.

Thanks anyway as you took time to report this!
