### ISSUE TITLE
Garbled characters are displayed

### ISSUE THREAD

**Issue by cyatarow** [zDevelopers/ImageOnMap#168]
ImageOnMap: v4.1.2
Minecraft: 1.16.5
Language: Japanese

Config.yml:
```
# Plugin language. Empty: system language.
# Available: en-US (default, fallback), fr-FR, ru-RU, de-DE, zh-CN, ja-JP.
lang: <This bug occurs in both ja-JP and en-US.>
```

![image](https://user-images.githubusercontent.com/26016252/115105617-15d59c00-9f9b-11eb-9b39-d61b0d3a3913.png)

**Comment by hui2007** [comment]
I changed the language to zh-CN and it has the same error!

**Comment by Vlammar** [comment]
I don't read chinese nor japanese, those characters are useless or are they replacing good one? I don't have this issue in en-US . It may be linked to an encoding issue in your server starting script. You had to specify the encoding with the argument `-Dfile.encoding=UTF-8` in your start.bat or start.sh script. Do you use an alternate encoding for chinese or japanese ?

**Comment by cyatarow** [comment]
>those characters are useless or are they replacing good one?

They are useless.

>Do you use an alternate encoding for chinese or japanese?

I don't know what encoding is set by default.

My start.bat:
```
@echo off
java -Xms1G -Xmx1G -jar spigot-1.16.5.jar nogui
pause
```

I added the UTF-8 argument, and this bug was fixed.

**Comment by Vlammar** [comment]
Nice! I will look this if it's solved.
