### ISSUE TITLE
using splatter maps in a grindstone gives unlimited xp

### ISSUE THREAD

**Issue by elisttm** [zDevelopers/ImageOnMap#169]
splatter maps being enchanted for cosmetic effect means they can be put into grindstones and harvested for xp. because you can create an unlimited amount of these, this means you can get effectively unlimited xp which is a huge balancing issue on smp servers

**Comment by AmauryCarrade** [comment]
This was fixed with the latest ImageOnMap version. In what version was this observed?

**Comment by elisttm** [comment]
> This was fixed with the latest ImageOnMap version. In what version was this observed?

the server is using imageonmap 4.1.2 which is the latest at least on spigot

**Comment by AmauryCarrade** [comment]
Okay, we reproduced. This problem was fixed on QuartzLib side but we forgot to use the fixed APIs here.
That _should_ be an easy fix. Thanks for reporting!

[ Ref. #116 ]

**Comment by Vlammar** [comment]
Will be fixed in 4.1.3.
