### ISSUE TITLE
Single tile images not placeable

### ISSUE THREAD

**Issue by MysticGrove** [zDevelopers/ImageOnMap#175]
Before, we were able to place single item frame sized maps but now it just deletes them immediatley upon placing in the frame. same goes for if its a frame from a larger painting or if its one rendered as a single tile. this also may be related but i was placing a bigger map on the floor and the bottom left tile seems to rotate twice upon placing which isnt extremley annoying. also roof maps you have to place on the top left tile instead of bottom left. niether of those are huge problems for me just insight on our specific situation if it would help you.

**Comment by Chalvrae** [comment]
I'm having same problem ever since i updated plugin to 4.1.2. I hope it can be solved somehow, because maps keep disappearing from server.

**Comment by Vlammar** [comment]
Are you using Paper ? And it look like this issue #174

**Comment by MysticGrove** [comment]
yes i am using paper

**Comment by kuraiskrap** [comment]
i was gonna make a bug report, but it looks like this already exists, hopefully the added details help with duplicating

when you place a map, **it consumes 2 maps**, if your only **holding one it gets deleted**
splatter maps are ok, effects standalone or single parts of splattermaps
does not effect if placed from **off hand**
does not effect normal in game maps
does not effect players in creative, **only in survival**

rolled back from 4.1.2
continued in 4.1.1
4.1 used 2 maps still, but wouldnt delete a placed map when you only held one
4.0 works fine
using java 11
tried removing every plugin besides essentials
useing paper, tried a 153 86 old version and current version
and the panel is pyrodactyl

**Comment by Vlammar** [comment]
Fixed on the actual update/1.17 branch
