### ISSUE TITLE
[Contribution] Spanish Translations

### ISSUE THREAD

**Issue by forerosantiago** [zDevelopers/ImageOnMap#182]
Hello, I want to contribute to this plugin by translating it to Spanish, I know I have to create a file [here](https://github.com/zDevelopers/ImageOnMap/tree/indev/src/main/resources/i18n) do I have to do anything else somewhere?

**Comment by Vlammar** [comment]
You also have to add to this commented line the code for spanish https://github.com/zDevelopers/ImageOnMap/blob/indev/src/main/resources/config.yml#L5 That's all that is needed :)

**Comment by forerosantiago** [comment]
All right, the pull request is #183 

Thank you.
