### ISSUE TITLE
Can't create new map

### ISSUE THREAD

**Issue by Peiprjs** [zDevelopers/ImageOnMap#189]
I'm on 1.16.5, and when I try to rrender a map it says: Map rendering failed:  java.lang.NullPointerException
I've set the language yet again to en-us, as the error suggests it could be a fault of that.

**Comment by Vlammar** [comment]
Can you provide the full log for the error ?

**Comment by Peiprjs** [comment]
I have already deleted the mod, as well as most of the logs from a week
ago. I'll try to do it later..

Missatge de Vlammar ***@***.***> del dia dg., 13 de juny 2021
a les 2:14:

**Comment by SHDocter** [comment]
consoleerror：WARN: [ImageOnMap] Rendering from Hurize failed: java.util.concurrent.ExecutionException: java.lang.NullPointerException

**Comment by SHDocter** [comment]
![image](https://user-images.githubusercontent.com/72510879/122187933-15398300-cec2-11eb-8d8c-02779093a4ed.png)

**Comment by AmauryCarrade** [comment]
We'll keep this in mind while migrating everything to 1.17, thanks! But this one is new, were you on a Spigot-based server?
