### ISSUE TITLE
Could not initialize class java.awt.Graphics.Environment$LocalGE

### ISSUE THREAD

**Issue by Chickblock2** [zDevelopers/ImageOnMap#190]
When I went to do /tomap https://i.ibb.co/qnYhLbN/DA44649-C-9-B63-4-B19-A1-EF-13-A1938-A7-FE9.png I got an error in chat saying "Map rendering failed: Cloud not intilize class java.awt.Graphics.Environment$LocalGE"
Console just says the same message. Any ideas?

**Comment by Vlammar** [comment]
You need to add -Djava.awt.headless=true in your starting script file.

**Comment by Chickblock2** [comment]
K thanks I will try that

**Comment by Chickblock2** [comment]
It worked
