### ISSUE TITLE
1.17 support?

### ISSUE THREAD

**Issue by maidado** [zDevelopers/ImageOnMap#191]
Plugin is not working on Servers running Spigot 1.17
"Map rendering failed: java.lang.NullPointerException: Cannot read field "mapView" because "worldmap" is null"

And existing Maps contain missing pixels

**Comment by Vlammar** [comment]
"Map rendering failed: java.lang.NullPointerException: Cannot read field "mapView" because "worldmap" is null" this issue come from spigot, we can no longer create maps. 
For the pixels that's probably like the last time they forget to update the color used for maps :/

**Comment by maidado** [comment]
can the map creation issue be fixed? :'(

**Comment by Vlammar** [comment]
Not right now, we have to wait spigot to update. After each update they usally break maps, that's because it's less critical and easier to fix

**Comment by Vlammar** [comment]
Spigot has updated and fixed the issue on their side. But some part have broken and we still need to check if everything is ok. 4.1.3 should be compatible with 1.17

**Comment by AllyTally** [comment]
Is there an ETA on 4.1.3?

**Comment by Vlammar** [comment]
At least one week. Every part that used Reflection is broken currently, and I still have to update QuartzLib https://github.com/zDevelopers/QuartzLib/tree/fix/1.17_compatibility.

**Comment by AllyTally** [comment]
Are there any updates on this? Sorry if you'd rather me not ask, it's just that my server really likes the plugin so they're wondering when it's coming back.
