### ISSUE TITLE
Problem with item frames on 1.17

### ISSUE THREAD

**Issue by etmclovin** [zDevelopers/ImageOnMap#192]
Whenever i make a make using /tomap it creates it fine but if it is over 1x1 and i try to put it on a item frame it doesnt fill all of them and when i take it back it disappears.  This only started happening after i upgraded to 1.17

**Comment by AmauryCarrade** [comment]
ImageOnMap is not yet compatible with 1.17. While upgrading (when Spigot and Paper's maps support will be ready) we'll keep an eye on this. Thanks!

Related: #191

**Comment by Vlammar** [comment]
This is caused by splatermap that is no longer working. 1.17 has changed the path to the class used by the reflection. For this specific case we have an issue with **ItemStack** The old path format was  ` net.minecraft.server.v1_17_R1.ItemStack` and now we use `net.minecraft.world.item.ItemStack` .

**Comment by etmclovin** [comment]
Is there an ETA on the fix?

**Comment by AmauryCarrade** [comment]
Closed on behalf or #198
