### ISSUE TITLE
Worldmap issue 

### ISSUE THREAD

**Issue by Vorald** [zDevelopers/ImageOnMap#199]
Hi, it's the first time I use this pluggin and whenever I try to make a map, I get this code in the chat:
Map rendering failed: java.lang.NullPointerException: Cannot read field "mapView" because "worldmap" is null 

Could someone help me ? 
Thanks

**Comment by AmauryCarrade** [comment]
You're using 1.17, right?

**Comment by Vorald** [comment]
> You're using 1.17, right?

yes I am

**Comment by AmauryCarrade** [comment]
Okay so this falls under #198. I'm closing this one because we keep only one issue for 1.17 compatibility :) Thanks!
