### ISSUE TITLE
SplatterMaps can be duplicated infinite times.

### ISSUE THREAD

**Issue by TomLewis** [zDevelopers/ImageOnMap#202]
ImageOnMap 3.1
Paper 1.12.2

Read the report & video here.

https://github.com/PirateCraft/dev/issues/155

I cant seem to see any permission to disable shift+click for players to prevent duplications? is my only option to remove the plugin as no later version works with 1.12.2?

**Comment by Vlammar** [comment]
Hello, we no longer  support 1.12. The plugin is on a BSD Licence, you are allowed to edit the code.
