### ISSUE TITLE
Map has a right size but can't be placed

### ISSUE THREAD

**Issue by Angrasion52** [zDevelopers/ImageOnMap#205]
So i have a problem with this Plugin. When i render a map i resize it with a size 2x2 and then the map rendered and i get the map, but when i place a item frame size 2x2 it said it need 2x2 item frame, please can someone fix this?

**Comment by lusterofgem** [comment]
I have the same problem. (pluginVersion:4.1.2, spigotVersion:1.17.1)

**Comment by Vlammar** [comment]
See #198
