### ISSUE TITLE
more maps

### ISSUE THREAD

**Issue by Dobby-progam** [zDevelopers/ImageOnMap#206]
when I have a fore example 
3X3 map  It don't show up 
![afbeelding](https://user-images.githubusercontent.com/87517487/126185711-c4676720-ceca-49d8-927c-0ad2486cfe33.png)
![afbeelding](https://user-images.githubusercontent.com/87517487/126185798-8364d584-b864-4b63-91ea-29373571e0b3.png)
thanks fore reading and I hope It is good

**Comment by Dobby-progam** [comment]
the server restar don't work

**Comment by Vlammar** [comment]
1.17 issue already known. Please see #198
