### ISSUE TITLE
Map doesn't work when placed on bottom left corner..

### ISSUE THREAD

**Issue by MstrCodeGeek** [zDevelopers/ImageOnMap#209]
Hey, So the map doesn't work when I click it in (1.17) item frame, only thing which works is I need to convert it to 1x1.

**Comment by voigtman** [comment]
I have the same issue on 1.17.1, 
The workaround seems to be to go to your /maps and click on the desired map and select each map and place them manually...

**Comment by MCnoob24** [comment]
@voigtman @MstrCodeGeek ImageOnMap isn't compatible with 1.17+ yet.

**Comment by Vlammar** [comment]
Known issue, see #198
