### ISSUE TITLE
It goes away when the server is restarted

### ISSUE THREAD

**Issue by AICentralYT** [zDevelopers/ImageOnMap#210]

**Comment by voigtman** [comment]
Same - to help the author: what I have happening on 1.17.1 is when a map is placed manually (cannot use splatter maps, see issue 209) the image initially appears fine. After server restart, the maps totally disappear, however when walking up to the item frame it still shows the column and row number. If you try to place another map it just vanishes.

**Comment by Vlammar** [comment]
Ok thx for the details. I assume it's part of the issues with 1.17. I lock it and add it to #198
