### ISSUE TITLE
image disappearing

### ISSUE THREAD

**Issue by vvlf** [zDevelopers/ImageOnMap#211]
Hey! I play on an apex hosted minecraft server with this plugin, and my friends and I have a reoccurring issue. We have the latest version of the plugin. Whenever we place an image that is resized to be 1 single frame, taking it out and attempting to put it back onto the frame or another frame makes it disappear. You can't get it off the frame again, as it seems to just disappear completely. When you pick it up, it's in your inventory but the moment it's placed on a frame it vanishes.

**Comment by Vlammar** [comment]
I may have an idea of what is causing this issue.

**Comment by Vlammar** [comment]
This issue may have been fixed in 4.2.1 See https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.2.1
