### ISSUE TITLE
map won't render

### ISSUE THREAD

**Issue by PoggeringIan** [zDevelopers/ImageOnMap#212]
me and my friends started an modded  smp with 4 mods only and i wanted to make an map for our business but I can't it sayed "Map rendering failed: java.lang.NullPointerExeption". I used an imgur link but the image is inappropriate. Im just gonna leave the image here... https://imgur.com/neaIv1M

**Comment by Vlammar** [comment]
Be aware that IoM support spigot/Paper some bukkit implementation for forge sadly doesn't implement the map API. That's not something we can fix. The bukkit API say that when you call Bukkit.getMap you should always get a map but with some implementation they simply doesn't care and don't return any map.
