### ISSUE TITLE
image not completing

### ISSUE THREAD

**Issue by Spottierfriend** [zDevelopers/ImageOnMap#217]
I'm in 1.17.1 with 1.4.2 of imageonmap and the image is showing whatever the splatter map is, but when I put it in item frames it doesn't show up.

**Comment by Vlammar** [comment]
@Spottierfriend you should try the 4.2.0 that's on prerelease status. https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.2.0

**Comment by SilverHammer09** [comment]
hi im having the same problem in 1.17.1  im on 4.1.2 for the image on map verson i recently got my server to 1.17 and never had a problem in 1.16 but now its having problems should also do 4.2.0?

**Comment by Vlammar** [comment]
Fixed in 4.2.0 and 4.2.1 for 1.18
https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.2.1
