### ISSUE TITLE
Map rendering failed: HTTP error: 429 Unknown Error

### ISSUE THREAD

**Issue by BastikLol** [zDevelopers/ImageOnMap#218]
I downloaded the ImageOnMap plugin onto my server, and I made a new imgur link (which links to an actual image). However, when I tried to do /tomap (link), it said this error: Map rendering failed: HTTP error: 429 Unknown Error

**Comment by Vlammar** [comment]
The HTTP 429 error is thrown when you do too many request. Try again later on a different website.
