### ISSUE TITLE
Tell player in chat when a link errors.

### ISSUE THREAD

**Issue by lasercar** [zDevelopers/ImageOnMap#22]
The `/tomap` command should tell a player the error when a link errors. For example, someone did `/tomap` and in the console I could see that the url had a 403 error. However, the player didn't know this because the error didn't show in chat for that player.

**Comment by prokopyl** [comment]
This has been implemented in b5d41b25d047d0b6592462c2c10bb0a82375331c. The HTTP error code is now clearly shown, both to the player and in the server console.
