### ISSUE TITLE
Maps limit reached, Help me, please

### ISSUE THREAD

**Issue by JIa6PaDoP** [zDevelopers/ImageOnMap#220]
I have reached the maps limit, what should I do now?
![2021-11-15_20 41 05](https://user-images.githubusercontent.com/94392794/141828805-cd2a3fb4-d3d6-49f7-848f-f0736c60c0e8.png)

**Comment by Vlammar** [comment]
What is your minecraft and IoM version? Are you on spigot or paper?

**Comment by JIa6PaDoP** [comment]
> What is your minecraft and IoM version? Are you on spigot or paper?

(Sorry, i'm russian) i didn't understand, what is "loM", My server on spigot
Minecraft version 1.12.2 OptiFine

**Comment by Vlammar** [comment]
IoM is for Image on Map (it's my bad)

**Comment by JIa6PaDoP** [comment]
Previously, the maps worked fine, apparently my friends and I rendered them a lot and reached the limit (32,767)

**Comment by JIa6PaDoP** [comment]
loM - it is version of plugin?

**Comment by JIa6PaDoP** [comment]
If so, then I have a version ImageOnMap-3.1

**Comment by Vlammar** [comment]
What will happen is when you reach the limit every new maps created will override older maps but I don't know how this version behave exactly. You may try to remove some maps. This should up some space for new one

**Comment by JIa6PaDoP** [comment]
I have already tried to delete maps from the plugin folder, even completely removed the plugin and installed it. I also deleted map_1.dat, map_2.dat... etc, from the /world/data folder, nothing helped

**Comment by JIa6PaDoP** [comment]
the question is closed, I have found a solution https://www.reddit.com/r/2b2t/comments/7ro854/4294967296_is_the_map_limit_in_113/
