### ISSUE TITLE
Splatter Maps not working (latest ver of imageonmap as of now and 1.17)

### ISSUE THREAD

**Issue by Ethan292939** [zDevelopers/ImageOnMap#223]
Every time I try to use a splatter map, it only places the top left square of the image and doesn't splatter. I'm hosting my server on serverminer if that changes anything. The single block maps work, but anything bigger than that just places the top left corner map. 

![image](https://user-images.githubusercontent.com/89052507/142802083-9816512e-ba8b-4c7f-ae4b-867fae132503.png)

Right now, my maps look like this (above)

the original image should be this:
![image](https://user-images.githubusercontent.com/89052507/142802145-cda65e18-fa82-4054-865b-78866fe7dd72.png)

**Comment by Ethan292939** [comment]
Also, just FYI the map is disenchated when I receive it in my inventory after running tomap. I'm not sure if that will change anything, but just FYI

**Comment by Ethan292939** [comment]
![image](https://user-images.githubusercontent.com/89052507/142802258-5d42dd21-e49d-4161-a555-e57ec96d9a57.png)

**Comment by Vlammar** [comment]
Fixed in https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.2.1.
