### ISSUE TITLE
can we save maps actually to map_x.dat files?

### ISSUE THREAD

**Issue by anar4732** [zDevelopers/ImageOnMap#226]
can we save maps actually to map_x.dat files to see the maps without the plugin or in singleplayer?

**Comment by Vlammar** [comment]
No but that's planned for the 5.0.0. No actual ETA but I started working on this feature. I don't know if bukkit as a tool that allow to do this. I started to look at using nms but I don't know if that is the best way of doing it. (maybe editing by hand the map_x.dat file is better)
