### ISSUE TITLE
An internal error occured while attempting to perform this command (1.18)

### ISSUE THREAD

**Issue by ZeroBelowZero** [zDevelopers/ImageOnMap#228]
Version: 4.2.0
MC Version: 1.18

Whenever I attempted to render an image this happens

![image](https://user-images.githubusercontent.com/90361688/144686668-88a7b95d-56c9-4096-be29-d8b6f33e33b3.png)

03.12 18:45:53 [Server] ERROR null
03.12 18:45:53 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'maptool' in plugin ImageOnMap v4.2.0
03.12 18:45:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
03.12 18:45:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
03.12 18:45:53 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2201) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2012) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1993) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
03.12 18:45:53 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-"1f5b013"]
03.12 18:45:53 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
03.12 18:45:53 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class fr.zcraft.imageonmap.quartzlib.tools.reflection.NMSNetwork
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.tools.text.MessageSender.sendChatPacket(MessageSender.java:600) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.tools.text.MessageSender.sendMessage(MessageSender.java:197) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.tools.text.MessageSender.sendActionBarMessage(MessageSender.java:476) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.tools.text.ActionBar.sendPermanentMessage(ActionBar.java:66) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.moribus.imageonmap.commands.maptool.NewCommand.run(NewCommand.java:156) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.components.commands.Command.execute(Command.java:322) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.components.commands.CommandGroup.executeMatchingCommand(CommandGroup.java:175) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.components.commands.CommandGroup.executeMatchingCommand(CommandGroup.java:169) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at fr.zcraft.imageonmap.quartzlib.components.commands.CommandGroup.onCommand(CommandGroup.java:190) ~[ImageOnMap-4.2.0.jar:?]
03.12 18:45:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
03.12 18:45:53 [Server] INFO ... 21 more

**Comment by romanobro56** [comment]
✋ I too am having this problem

**Comment by Vlammar** [comment]
I'm working on the 1.18 support that will be included to the 4.2.1. I still have to fix issues with NBT tags that are not kept after restarting the server

**Comment by Vlammar** [comment]
Fixed in 4.2.1 see https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.2.1
