### ISSUE TITLE
/maptool reload command to reload configuration

### ISSUE THREAD

**Issue by ErythroCraft** [zDevelopers/ImageOnMap#265]
Hello.

Missing [/maps reload] command, to reload the configs.

Maybe you can create an update to do that.

**Comment by AmauryCarrade** [comment]
Hi,

We don't have plans to add such command currently as there is not enough requests or needs to it, but if you do need this command, feel free to contribute, this is open source software :) .

**Comment by ErythroCraft** [comment]
Sorry. But I can't do this. I don't know, how.
