### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by VanzzHikz** [zDevelopers/ImageOnMap#293]

**Comment by AmauryCarrade** [comment]
Could you elaborate?

If you received a 429 error trying to render a map, it’s not a plugin bug, it’s [a response from the server](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) saying: « you requested too many images in a short amount of time; please stop for a moment » (_rate-limit_)

**Comment by AmauryCarrade** [comment]
Closing for now as it’s probably out-of-scope, but feel free to reopen if I got this wrong.
