### ISSUE TITLE
Specify resizing size

### ISSUE THREAD

**Issue by ghost** [zDevelopers/ImageOnMap#42]
I would like to have the possibility to specify a resizing splatter map size.
The command could look like this: `/tomap https://imgur.com/1234 resize 4 2` where 4 would tell the plugin to generate a 4 high splatter map and and 2 would specify the height.

**Comment by AmauryCarrade** [comment]
4.0-pre1 (including 1.13 and 1.14 support) [has been released](https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.0-pre.1) and this feature is now available (with the exact same command) :) .
