### ISSUE TITLE
Image IDs messed up after server properties file changed

### ISSUE THREAD

**Issue by QixyQix** [zDevelopers/ImageOnMap#44]
My server.properties file was changed one day where the selected level name was reset to the default configuration ("world")

This resulted in many of the maps that were previously created to break, all my previous poster maps now show regular minecraft maps or are displaying parts of the wrong image. 

My console showed no errors as well

**Comment by AmauryCarrade** [comment]
Minecraft uses the default world to look for map files, regardless of the world the map was created one. You could try to copy the files from the old world folder to the new one (they are located in the data sub-folder).

We could try to detect the change of default world to copy the maps automatically but it could have side effects. This should totally be documented, at least.

This is somewhat related to #31.

20 février 2018 10:31 "QixyQix"  a écrit:
	My server.properties file was changed one day where the selected level name was reset to the default configuration ("world") 

	This resulted in many of the maps that were previously created to break, all my previous poster maps now show regular minecraft maps or are displaying parts of the wrong image.

**Comment by QixyQix** [comment]
The change in the default world in the server properties file was not really intended as it was reset without my knowledge after a server crash.

I restored the server properties file but it did not really do anything to help either.

**Comment by AmauryCarrade** [comment]
Was this resolved? I failed to see your answer, I'm really sorry (yeah, one year and a half later…)

**Comment by QixyQix** [comment]
No, it was not. Doesn't seem to have happened again though so far. Any 1.12/13/14 update coming soon?

**Comment by AmauryCarrade** [comment]
1.13 & 1.14 pre-release is available in the releases tag or on SpigotMC :)

And ImageOnMap 3.1 should be compatible with 1.12, but I'm not supporting this version anymore (and 4.0 only support 1.13+).
