### ISSUE TITLE
Old version on DevBukkit

### ISSUE THREAD

**Issue by bibo38** [zDevelopers/ImageOnMap#47]
Currently only the 3.0 version is available via [DevBukkit](https://dev.bukkit.org/projects/imageonmap/files).

**Comment by Vlammar** [comment]
@AmauryCarrade Did you manage to get back your credentials from devbukkit ?

**Comment by AmauryCarrade** [comment]
No (or maybe not yet, but I don't know).

**Comment by Vlammar** [comment]
No longer an issue, we have taken back the account

**Comment by AmauryCarrade** [comment]
Still an issue, I still have to update the version and its description there.

**Comment by AmauryCarrade** [comment]
[Done!](https://dev.bukkit.org/projects/imageonmap/files/2972262)
