### ISSUE TITLE
Map Duping

### ISSUE THREAD

**Issue by Iyoforeayo** [zDevelopers/ImageOnMap#54]
Is there a way to configure it so that players can _only_ remove a placed splatter map by shift-left-clicking, and not be able to break individual maps in the image? Currently, if a player breaks each individual image regularly, then they can use each of those individually broken maps as a full splatter map, and essentially dupe the splatter map infinitely.

**Comment by AmauryCarrade** [comment]
Maps have no survival value and players can get a copy of already rendered maps in `/maps`, so is this really needed?

**Comment by Iyoforeayo** [comment]
On our server, maps do have survival value - but we've since switched to a different plugin, so this is no longer needed for us (though I imagine we're not the only server to assign value to map items, so might be useful functionality for others in the future)
