### ISSUE TITLE
Map Rendering Failed

### ISSUE THREAD

**Issue by cinimodphoto** [zDevelopers/ImageOnMap#62]
I uploaded an image 1024x1024 both a jpg and a png to imgur I have the link when I try the link it just gives me the error "Map rendering failed: The given URL is not a valid image" I have no clue what I am doing wrong. I have tried different sizes, different images and even saving the image publicly on imgur not just url grabbing.  Here is the most recent image url. https://imgur.com/ZGIuWGa

**Comment by cinimodphoto** [comment]
Update to ticket, restarted server and now no error at all just says /tomap [URL] in all white. Here is the full command. /tomap i.imgur.com/ZGIuWGa.png That is what I am using.

![image](https://user-images.githubusercontent.com/58937962/70903530-edf3b400-1fb3-11ea-9e07-604379e1cc45.png)

**Comment by AmauryCarrade** [comment]
Hi!

For the first issue, please make sure that the URL is a valid URL to _the image itself_: https://i.imgur.com/ZGIuWGa.png would do the trick (note the `https://`). The link to the Imgur webpage containing the image is _not_ valid.

For the second part, it looks like the plugin is not correctly loaded for some reason. Is there something in the console?

**Comment by Vlammar** [comment]
@cinimodphoto Up ?

**Comment by cinimodphoto** [comment]
So I reinstalled my server with 1.15 instead of 1.15.1 I put ImageOnMap-3.1.jar on my server. When I do /tomap [url] which the most recent I used was https://i.imgur.com/VxCmLYB.png it shows in chat Rendering... Then shows Rendering finished!  The issue now is it is not producing a map I then tried same command  but with resize  then the same command with resize 3 2 they all say the same thing Rendering... Rendering Finished but I do not get a map. I have tried as an OP player with rank Owner all the way down to non op rank starter. I have even tried the command from the console. I have tried holding a map in my hand still no luck. In the ImageOnMap folder under maps there is a file in there that looks like it takes and the images folder has images in it from the image that I used from imgur yet still nothing.

**Comment by cinimodphoto** [comment]
So I tried deleting the jar and folder and installed the new ImageOnMap-4.0.jar it created a folder loaded and when I use the same command it instead of in chat telling me says it in floating text that it is rendering and then finished still no map. When I do /maptools list it says each time a new number of maps found but each time then says "An internal error occurred while attempting to perform this command"

**Comment by Vlammar** [comment]
The current version of IoM does not support 1.15 yet. It's linked to this https://github.com/zDevelopers/zLib/issues/23 , we are currently working on the issue with zLib, I will try to fix this weekend. Hopefully IoM 1.15 will be released soon after zLib update.
Note: You can run your server in 1.15 with IoM not working when the plugin will be compatible you won't lose previous maps.

**Comment by cinimodphoto** [comment]
Ohh then I wonder what plugin the SMP Earth team is using that CaptainSparklez plays on cause they are on 1.15.1 and it works for them. I cant remember what theirs is called I will have to watch some of their VODs. Thank you. I really do hope you get a 1.15 version soon that would be amazing.

**Comment by Vlammar** [comment]
Update: We may be posting the new version compatible with 1.15 this week-end.

**Comment by cinimodphoto** [comment]
Yay

**Comment by Vlammar** [comment]
The release for the 1.15 have been made, you can find it here https://www.spigotmc.org/resources/imageonmap.26585/
