### ISSUE TITLE
1.15 support!

### ISSUE THREAD

**Issue by pixelflowxyz** [zDevelopers/ImageOnMap#67]
Hey everyone!

Just wondering when/if 1.15 support will ever be added? I love this plugin and the server I use it on is looking to upgrade.. any ETA on when it'll be supported?

**Comment by AmauryCarrade** [comment]
I hope to be able to work on this this week or the next one. I'm pretty busy but I'm doing my best!

Thanks for your patience :) .

**Comment by pixelflowxyz** [comment]
No worries - I know development can be hard with other stuff going on, and even harder when it's rushed.
Take your time, we've upgraded with IOM currently and it's good. :) <3
