### ISSUE TITLE
/maps throwing Achievement-related exception

### ISSUE THREAD

**Issue by luckybl0ck** [zDevelopers/ImageOnMap#72]
When using /maps, the plugin throws an error. https://hasteb.in/axobidap.md

**Comment by Vlammar** [comment]
What is your version? And you are on paper ?

**Comment by luckybl0ck** [comment]
This server is running Paper version git-Paper-105 (MC: 1.15.2)

**Comment by Vlammar** [comment]
Did you build the .jar yourself?

**Comment by luckybl0ck** [comment]
No, I downloaded the plugin from the Releases tab

**Comment by AmauryCarrade** [comment]
That's weird. We'll look into it… This bug should have been fixed long ago and `/maps` is working on our side. Maybe an edge case…

**Comment by luckybl0ck** [comment]
This can't happen because of a datapack with achievements installed on the server?

**Comment by Vlammar** [comment]
This is very unlikely. I didn't achieve to get the same error make sure to use this version of the plugin: https://www.spigotmc.org/resources/imageonmap.26585/download?version=314302

**Comment by luckybl0ck** [comment]
This version works, thank you.

**Comment by AmauryCarrade** [comment]
That was really, really weird as these versions are exactly the same:

```
$ sha1sum ImageOnMap*.jar
49d027ba2e98387d7ee6eaf4a16d9d1021ab3f6a  ImageOnMap-4.0-pre2-gh.jar
49d027ba2e98387d7ee6eaf4a16d9d1021ab3f6a  ImageOnMap-4.0-pre2-spigot.jar
```

But well, it works, so that's fine, let's hope we don't have the same problem again :)
