### ISSUE TITLE
"Rendering" text stays on screen when map render fails

### ISSUE THREAD

**Issue by James76931** [zDevelopers/ImageOnMap#75]
Hi.

When the map rendering fails due to a user meeting their map quota ("You have too many maps...") the green "Rendering..." text above the hotbar does not disappear.

![](https://cdn.discordapp.com/attachments/372503236088823808/689938305332019257/unknown.png)

**Comment by Vlammar** [comment]
Duplicate of https://github.com/zDevelopers/ImageOnMap/issues/71
We are aware of this issue, I don't plan to fix it for 4.0, that will be the case for 4.1
