### ISSUE TITLE
Dependency problems

### ISSUE THREAD

**Issue by marcjosephstreeter** [zDevelopers/ImageOnMap#83]
The Dependency doesn't load it gives me this error:Could not find artifact fr.zcraft:zlib:pom:0.99-SNAPSHOT in spigot-repo I tried to check out the tag for version 3.0 and it still doesn't work.

**Comment by Vlammar** [comment]
Master is not up to date yet, we are on the 1.15 branch for zLib and the actual version is currently 1.0

**Comment by marcjosephstreeter** [comment]
Thank you for the reply :) I'm a little new to java, should I build this and make this available to this package somehow? Could you point me too a good resource on how to do that?

**Comment by Vlammar** [comment]
For now (until maven repo is alive)you can do as me, use local package, for this you have to make sure you got the 1.15 branch of zLib then you run the following command tobuild IoM and zLib 

> cd zLib && mvn clean install && cd ../ImageOnMap && mvn clean install
Then voila :)

**Comment by Vlammar** [comment]
Does this work ? @marcjosephstreeter
