### ISSUE TITLE
Treasure maps losing X's

### ISSUE THREAD

**Issue by Pugabyte** [zDevelopers/ImageOnMap#85]
ImageToMap seems to be causing treasure maps to not have X's on them. 1.15 Paper

**Comment by Vlammar** [comment]
It's Image**On**Map github, is this a typing error ?

**Comment by Pugabyte** [comment]
Yes, sorry

**Comment by Vlammar** [comment]
Are you using a ressource pack of some sort ?

**Comment by Pugabyte** [comment]
No texture pack. Dozens of players reporting the issue until we removed ImageOnMap. This was reported on your spigot page as well.

**Comment by Nety01** [comment]
Ye I had similiar problem, not losing X, but the X going to somewhere where the treasure is NOT. Confirmed many times. At this moment ImageOnMap is unfortunately totally unusable for us with those another issues out of this one.

**Comment by GriffinCodes** [comment]
I am no longer experiencing this issue with 4.0
