### ISSUE TITLE
Question: How safe is this to use with dtltraders to sell maps to players?

### ISSUE THREAD

**Issue by FrozenBeard** [zDevelopers/ImageOnMap#88]
Hello! Brand new to this, im using ImageOnMap 3.1 on Paper 1.12.2.
I have had an artist make some custom artwork for the server which I plan to sell to players using in-game money using dtltraders NPC, Ive genreated the map which has given me the item in-game and then ive put it in an dtltraders shop, which is all a GUI, and it saved NBT data for things like maps.

I have a question, is this safe? Will it create lag or issues if I sell these? Are these maps Tied to a Unique ID per map or something?

Is it safe to duplicate the maps using creative/an NPC?

Thanks

**Comment by Vlammar** [comment]
Hi. They will be able to place splatter map and retrieve them. Lag issue is unlikly, rendering is the only task that affect the server (if you do it on a 1000*200 that won't work or it will cause a lag spike (memory issue), if you stay in normal size you will never have issue). We use minecraft map ID given by bukkit api and we change the attached renderer to a new renderer, that's how we trick minecraft to print a picture. If the player is given a splatter map with all nbt data that should be fine and safe it's like giving a regular item.

**Comment by FrozenBeard** [comment]
Brilliant, thank you.
I wasn't sure if this was purely a plugin for admins to make items at spawn etc, or if it was made to allow distributing maps to players.

One more question, what happens if I give out maps to players and remove the plugin at a later date? Do the maps still work or does something happen to them?

**Comment by Vlammar** [comment]
If you remove the pluggin the maps revert to minecraft renderer but if you reinstall IOM maps will begin to render like normal.
